name: Manual Deployment Notice

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Notice
        run: echo "Deployment is currently handled manually by building locally and pushing the /docs folder."
